import { EventEmitter } from '../../stencil-public-runtime';
export declare class MortarDatepicker {
    label: string;
    error: string;
    haserror: boolean;
    open: boolean;
    min: Date;
    max: Date;
    dateToString: (date: any) => string;
    value: Date;
    valueString: string;
    mask: string;
    required: boolean;
    disabled: boolean;
    placeholder: string;
    name: string;
    header: boolean;
    selectDate: EventEmitter<Date>;
    clearDate: EventEmitter<void>;
    inputChange: EventEmitter<Date>;
    dateOutOfRange: EventEmitter<Date>;
    private calendarElement;
    private toggleElement;
    handleOpen: () => void;
    handleSelect: (evt: any) => void;
    handleClear: () => void;
    handleOutsideClick(evt: any): void;
    handleCalendarRef: (ref: any) => void;
    handleToggleRef: (ref: any) => void;
    handleClickDate: () => void;
    handleKeyboardSelect: () => void;
    handleKeyboardExit: () => void;
    setToggleFocus: () => void;
    handleBlur: (evt: any) => void;
    updateValueFromInput: (val: any, os: any) => void;
    componentWillLoad(): void;
    handleValue(v: any): void;
    render(): any;
}
