import { EventEmitter } from '../../stencil-public-runtime';
import { MortarDropdownItem } from '../mortar-dropdown-item/mortar-dropdown-item';
export declare class MortarDropdown {
    size: string;
    label: string;
    help: string;
    haserror: boolean;
    error: string;
    placeholder: string;
    disabled: boolean;
    open: boolean;
    focused: boolean;
    highlight: number;
    value: string;
    itemSelect: EventEmitter<Object>;
    el: HTMLElement;
    private dropdownEl;
    private options;
    className: () => any;
    dropClassName: () => any;
    displayClassName: () => any;
    handleClick: () => void;
    handleFocus: () => void;
    handleBlur: () => void;
    handleListClick: (evt: any) => void;
    handleItemSelect: (option: MortarDropdownItem) => void;
    handleOutsideClick(evt: any): void;
    handleDropdownRef: (ref: any) => void;
    componentWillLoad(): void;
    loadOptions: () => void;
    handleOpen(openValue: any): void;
    getAvailable: () => any[];
    getCurrent: () => MortarDropdownItem;
    clearHighlight: () => void;
    setHighlight: (next: any) => void;
    selectHighlight: () => void;
    handleKeySelect(evt: any): void;
    render(): any;
}
